version: "3.9"
services:
  mongodb_container:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27777:27017
    volumes:
      - ./mongodb-seeding:/mongodb-seeding
    command: mongod --noauth
