service: aws-node-express-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: ap-southeast-2

functions:
  express:
    handler: dist/express-handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  graphql:
    handler: dist/apollo-handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: dist/apollo-handler.playgroundHandler
    events:
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

package:
  exclude:
    - .gitignore
    - README.md
